
path:
  app.root: "."
  import: "xlsxToImport"
  imported: "${path.import}/imported"
  export: "exports"

spring:
  application:
    name: BbvaAdapter
  datasource:
    #url: jdbc:h2:mem:dev;MODE=PostgreSQL;
    url: jdbc:postgresql://localhost:5432/BbvaAdapter
    #driver-class-name: org.h2.Driver
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
      #naming:
       # implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          format_sql: true
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  liquibase:
    change-log: classpath:/config/liquidbase/master.xml